version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT:-5001}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=patientdb;Username=postgres;Password=postgres;
    depends_on:
      - db
    networks:
      - patient-network

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=patientdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - patient-network

networks:
  patient-network:
    driver: bridge

volumes:
  postgres-data:
